version: 2.1 # using 2.1 provides access to orbs and other features
orbs: # declare what orbs we are going to use
  node: circleci/node@4.1.0 # the node orb provides common node-related configuration
parameters:
workflows:
  test:
    jobs:
      - node/test:
          matrix:
            parameters:
              pkg-manager:
                - yarn
              override-ci-command:
                - yarn install --immutable
              version:
                - 15.8.0
                - 14.15.5
                - 12.20.2
                - 10.23.3
